### ISSUE TITLE
🐛 Inconsistency with the docs

### ISSUE THREAD

**Issue by akmal1606** [johannchopin/restapify#80]
I read the docs

> Restapify allow you to easily create REST API routes using a specific file structure. Take the following folder api/ for example:
> 
> 📂 api
> ┣ 📂 users
> ┃ ┗ 📜 _.json
> ┃ ┗ 📜 [userid].json
> ┃ ┗ 📜 [userid].DELETE.json
> ┣ 📂 posts
> ┃ ┗ 📜 [postid].json
> ┃ ┗ 📜 my-post.PUT.json
> ┣ 📜 posts.json
> It will serve the following routes:
> 
> GET    /users
> GET    /users/:userid
> DELETE /users/:userid
> GET    /posts
> GET    /posts/:postid
> PUT    /posts/my-post
> 

but when I tried using restapify list, I got like this, any config that I need ?

> GET    /users
> GET    /users/[userid]
> DELETE /users/[userid]
> GET    /posts
> GET    /posts/[postid]
> PUT    /posts/[my-post]

**Comment by johannchopin** [comment]
Hey @akmal1606 👋  Thanks for opening this issue 👍 

I'm a bit confused here because first I saw the inconsistency between the route `PUT /posts/my-post` and the displayed route `PUT /posts/[my-post]`. However I tried this example with the latest version v2.3.0 and it was working properly.

So I guess you are confused with the different notation `:` and `[]` to identify variables in a route. Restapify like nextjs or sveltekit uses in most places the `[]` notation. However I decided to use the well know convention of expressjs that uses `:` to avoid user's confusion in the first lines of the doc.

Do you think that it would be better to use the `[]` notation in the doc?

**Comment by akmal1606** [comment]
I think so. for consistency. 

btw @johannchopin can you help me to deploy this restapify to cloud ? or can we deploy it to vercel ?

**Comment by johannchopin** [comment]
Nice then lets make the update in the `/docs/README.md` file 👍  Do you want to take care of this one?

This question was already asked in #75 so I will try to spend some time to check how I could make restapify be hostable in a serverless architecture 👍

**Comment by johannchopin** [comment]
Fixed in 8c28979.
